/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/common/AppFooter.vue')['default']
    AppHeader: typeof import('./components/common/AppHeader.vue')['default']
    AppSidebar: typeof import('./components/common/AppSidebar.vue')['default']
    ArticleCard: typeof import('./components/article/ArticleCard.vue')['default']
    ArticleContent: typeof import('./components/article/ArticleContent.vue')['default']
    ArticleList: typeof import('./components/article/ArticleList.vue')['default']
    ArticleMeta: typeof import('./components/article/ArticleMeta.vue')['default']
    ArticleTags: typeof import('./components/article/ArticleTags.vue')['default']
    ArticleToc: typeof import('./components/article/ArticleToc.vue')['default']
    DailyLogCard: typeof import('./components/dailyLog/DailyLogCard.vue')['default']
    DailyLogTimeline: typeof import('./components/dailyLog/DailyLogTimeline.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    MarkdownEditor: typeof import('./components/editor/MarkdownEditor.vue')['default']
    PagefindSearch: typeof import('./components/search/PagefindSearch.vue')['default']
    ProjectCard: typeof import('./components/project/ProjectCard.vue')['default']
    ProjectList: typeof import('./components/project/ProjectList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillCloud: typeof import('./components/skill/SkillCloud.vue')['default']
    SkillItem: typeof import('./components/skill/SkillItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
